name: Testing
on: [push, pull_request]

jobs:
  test:
    name: Testing SketchKit
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: 12.0.0
      
      - name: Running SketchKit Unit Tests with the latest iOS version
        run: exec ./.github/scripts/test_app.sh latest

      - name: Running SketchKit Unit Tests with iOS 9
        run: exec ./.github/scripts/test_app.sh ios9
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1  
